# Generated by Django 5.1 on 2024-08-31 20:06

import datetime
import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("category", models.CharField(db_index=True, max_length=64)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity_sold", models.IntegerField()),
                (
                    "total_sales_amount",
                    models.DecimalField(decimal_places=2, max_digits=9),
                ),
                (
                    "date_of_sale",
                    models.DateTimeField(db_index=True, default=datetime.datetime.now),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.product"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
