# Generated by Django 5.1 on 2024-09-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
